// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvbFvlki17FPSlns7zmbWleWR_pV4xd5E',
    appId: '1:898489121871:web:7e8b201047c5d240fe7e3a',
    messagingSenderId: '898489121871',
    projectId: 'classmate-33790',
    authDomain: 'classmate-33790.firebaseapp.com',
    storageBucket: 'classmate-33790.appspot.com',
    measurementId: 'G-MC8V5KNMCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiyuG6TRqZBbsiMlNLGGO2n5KuXvdHw60',
    appId: '1:898489121871:android:a91b16c1b44a867efe7e3a',
    messagingSenderId: '898489121871',
    projectId: 'classmate-33790',
    storageBucket: 'classmate-33790.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLGCxAImxK0g8p8GWpPg14nG9KQuDHgMs',
    appId: '1:898489121871:ios:5f5919fa5bdf2582fe7e3a',
    messagingSenderId: '898489121871',
    projectId: 'classmate-33790',
    storageBucket: 'classmate-33790.appspot.com',
    iosBundleId: 'com.classmate.classMate',
  );
}
